development:
  adapter: mysql
  database: goals_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: goals_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: goals_production
  username: root
  password:
  host: localhost
